### ISSUE TITLE
Things in [brackets] render wrong

### ISSUE THREAD

**Issue by dreeves** [OneGraph/oneblog#16]
## Reseminata

1. Start a post by creating a gissue at https://github.com/OneGraph/essay.dev/issues like normal
2. Type something like "blah blah [this part in brackets] more blah blah"
3. Publish it (ie, submit the gissue!)

## Expectata

It renders the same way it does in the gissue.

## Resultata

It renders like this:

blah blah
this part in brackets
more blah blah

**Comment by dwwoelfel** [comment]
Thanks for the detailed report! It's fixed in this commit: https://github.com/OneGraph/oneblog/commit/5ab94d466d0ef624f72354a28b052f806f329191

It was being parsed as a "link reference" which is a weird markdown thing where you can define your links in a table (see below). I didn't know what they were and I wasn't rendering them properly. Now we render link references properly and render `this [part in brackets]` as `this [part in brackets]`.

```
Boy that [Beeminder][beeminder] sure is nifty!

[beeminder]: http://beeminder.com/ "Goal tracking that stings"
```
