### ISSUE TITLE
Title text (hovertext) on images displayed inline

### ISSUE THREAD

**Issue by dreeves** [OneGraph/oneblog#17]
## Reseminata (repro steps)

1. Include an image in your post like so:

```
<img class="aligncenter"
alt="A workerbee making an assembly line of humans do its bidding"
title="It's a worker bee making humans do its bidding. It will make sense if you read this post! In Soviet Russia, user support you."
width="450px"
src="https://blog.beeminder.com/wp-content/uploads/2020/10/faire-upsidedown-boss-bee.jpeg"/>
```

## Expectata (what was expected)

An image with alt text and title text, like the gissue shows.

## Resultata (what actually happens)

It renders with the title text shown as a caption, like so:

![image](https://user-images.githubusercontent.com/9928/99847194-8aabc380-2b2c-11eb-871f-c0b6d0846fb2.png)

**Comment by dwwoelfel** [comment]
@dreeves I made this a setting (`displayImageTItleAsCaption`) and set it to false for you. Now titles won't show up as captions for the beeminder blog. If you do want a caption, you can add a `data-caption` prop to your image tag.

I'd like to keep the behavior in general because it makes the migration path from Medium much nicer (e.g. https://stopa.io/post/218#the-fateful-email).
